spring:
  application:
    name: product-orchestration-service

server:
  port: 7000

logging:
  level:
    root: INFO
    com.microservices: DEBUG

app:
  service:
    product:
      host: localhost
      port: 7001
    review:
      host: localhost
      port: 7002
    recommendation:
      host: localhost
      port: 7003

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  service:
    product:
      host: product
      port: 8080
    review:
      host: review
      port: 8080
    recommendation:
      host: recommendation
      port: 8080