spring:
  application:
    name: product-orchestration-service

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  pathsToMatch: /**
  packagesToScan: com.microservices.core.product.orchestration

api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

server:
  port: 7000

logging:
  level:
    root: DEBUG
    com.microservices: DEBUG

app:
  service:
    product:
      host: localhost
      port: 7001
    review:
      host: localhost
      port: 7002
    recommendation:
      host: localhost
      port: 7003




---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  service:
    product:
      host: product
      port: 8080
    review:
      host: review
      port: 8080
    recommendation:
      host: recommendation
      port: 8080